
title: SecHOPE 2023
email: 
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sechope23.github.io" 

# Build settings
theme: minima

minima:
    - skin: auto

header_pages:
    - program.md
    - accepted_papers.md
    - cft.md
    - organization.md
